In [19]:
import requests
from dotenv import load_dotenv
load_dotenv()
import os
import pandas as pd
import sqlalchemy as alch
import numpy as np
import sys
sys.path.append('src')
import apidiscogs as apd
import time

In [20]:
tokendis = os.getenv("discog")

In [21]:
passw = os.getenv("mysql")
dbName = "musicablecero"
connectionData = f"mysql+pymysql://root:{passw}@localhost/{dbName}"
engine = alch.create_engine(connectionData)

In [22]:
albums = pd.read_sql_query(f"""
                   
                    select a.artist,b.album,b.id_alb
                    from albums b left join artistas a on b.id_art = a.id_art
                    where b.album is not null and a.artist <> 'Varios Artistas';
                    """
                    , engine)

In [23]:
#select a.artist,b.album,b.id_alb from albums b left join artistas a on b.id_art = a.id_art;

In [24]:
albums.sample(3)

                               artist                     album  id_alb
3917                     Niña Pastori                  Eres Luz    4027
921   Tom Petty and The Heartbreakers      You're Gonna Get It!     959
1160                        Tori Amos  From The Choirgirl Hotel    1206

In [25]:
# albumsprueba = albums.sample(20)

In [26]:
# albumsprueba['art_url'] = albumsprueba.artist.replace(' ','+',regex=True)
# albumsprueba['alb_url'] = albumsprueba.album.replace(' ','+',regex=True)

In [27]:
# lista = []
# for i,r in albumsprueba.iterrows():
#     dicc = {}
#     url = f'https://api.discogs.com/database/search?artist={r.art_url}&release_title={r.alb_url}&token={tokendis}'
#     req = requests.get(url).json()
#     if req['results'] == []:
        
#         dicc['id_alb'] = r.id_alb
#         dicc['gen'] = np.nan
#         dicc['genres'] = np.nan
#         dicc['subgenres'] = np.nan
#         lista.append(dicc)

#     else:
#         genero = req['results'][0]['genre']
#         subgenero = req['results'][0]['style']
#         dicc['id_alb'] = r.id_alb
#         dicc['gen'] = req['results'][0]['genre'][0]
#         dicc['genres'] = req['results'][0]['genre']
#         dicc['subgenres'] = req['results'][0]['style']
#         lista.append(dicc)

In [28]:
albums['art_url'] = albums.artist.replace(' ','+',regex=True)
albums['alb_url'] = albums.album.replace(' ','+',regex=True)

In [29]:
albums.head(5)

,artist,album,id_alb,art_url,alb_url
0,Siniestro Total,Made in Japan,1,Siniestro+Total,Made+in+Japan
1,Platero y tú,Hay Poco Rock & Roll,2,Platero+y+tú,Hay+Poco+Rock+&+Roll
2,Pablo Ager,Durmiendo En Azoteas,3,Pablo+Ager,Durmiendo+En+Azoteas
3,Luis Ramiro,Castigado En El Cielo,4,Luis+Ramiro,Castigado+En+El+Cielo
4,Niños Mutantes,Florecer,5,Niños+Mutantes,Florecer

In [30]:
albums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4146 entries, 0 to 4145
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   artist   4146 non-null   object
 1   album    4146 non-null   object
 2   id_alb   4146 non-null   int64
 3   art_url  4146 non-null   object
 4   alb_url  4146 non-null   object
dtypes: int64(1), object(4)
memory usage: 162.1+ KB

In [31]:
albums.sample(5)

,artist,album,id_alb,art_url,alb_url
1968,Doctor Explosión,Viviendo Del Cuento,2044,Doctor+Explosión,Viviendo+Del+Cuento
2783,Louis Prima,The Wildest!,2877,Louis+Prima,The+Wildest!
1478,Adam Sky,We Are All Prostitutes,1537,Adam+Sky,We+Are+All+Prostitutes
3512,Fito & Fitipaldis,Huyendo Conmigo De Mí,3619,Fito+&+Fitipaldis,Huyendo+Conmigo+De+Mí
3819,Estrella Morente,Autorretrato,3926,Estrella+Morente,Autorretrato

In [32]:
#probando = apd.generosdiscog(albumsprueba,albumsprueba.art_url,albumsprueba.alb_url,albumsprueba.id_alb)
lista = []
a=0
for i,r in albums.iterrows():
    
    lista.append(apd.generosdiscog(r.art_url,r.alb_url,r.id_alb))
    time.sleep(1)

15:('The+Beatles', 'Rubber+Soul') hecho
30:('Mägo+de+Oz', 'Gaia') hecho
45:('Tontxu', 'En+El+Nombre+Del+Padre') hecho
60:('Bon+Jovi', 'Cross+Road') hecho
75:('Celia+Cruz', 'Mi+vida+es+un+cantar') hecho
90:('The+Bangles', 'Different+Light') hecho
105:('Gala', 'Come+into+my+life') hecho
120:('Rocky+Sharpe+&+The+Replays', 'Rama+Lama') hecho
135:('Van+Halen', 'Balance') hecho
150:('Celtas+Cortos', 'Tranquilo+majete') hecho
165:('Roxette', "Don't+Bore+Us+-+Get+To+The+Chorus!+(Roxette's+Greatest+Hits)") hecho
180:('George+Harrison', 'Cloud+Nine') hecho
195:('Nirvana', 'In+Utero') hecho
210:('Bob+Marley+&+The+Wailers', 'Songs+of+Freedom') hecho
225:('Muchachito+Bombo+Infierno', 'Vamos+Que+Nos+Vamos') hecho
240:('La+Oreja+de+Van+Gogh', 'Dile+al+sol') hecho
255:('Chris+de+Burgh', 'Into+The+Light') hecho
270:('Fito+&+Fitipaldis', 'Vivo...+Para+Contarlo') hecho
285:('Outlandish', 'Bread+&+Barrels+of+Water') hecho
300:('Joaquín+Sabina', '19+Días+y+500+Noches') hecho
315:('Salvador+Amor', 'Qué+Nos+Pasó') hecho
330:('Joaquín+Sabina', 'Física+y+Química') hecho
360:('Billie+Myers', 'Growing,+Pains') hecho
375:('The+Pogues', 'If+I+Should+Fall+From+Grace+With+God') hecho
390:('Europe', 'Out+Of+This+World') hecho
405:('Bon+Jovi', 'New+Jersey') hecho
420:('Amaral', 'Amaral') hecho
435:('Tracy+Chapman', 'Fast+Folk+Musical+Magazine+(Vol.+3,+No.+4)+Boston+One') hecho
450:('Madness', 'Absolutely') hecho
465:('Mötley+Crüe', 'Dr.+Feelgood') hecho
480:('Warrant', "Cherry+Pie+all+the+Hitz+'n'+More") hecho
495:('Great+White', 'Rock+Me') hecho
510:('Seguridad+Social', 'Furia+latina') hecho
525:('Pedrito+Fernández', 'Cielito+Lindo') hecho
540:('The+Baseballs', 'Strike!+Back') hecho
555:('Mike+&+The+Mechanics', 'Beggar+on+a+Beach+of+Gold') hecho
570:('Pabellón+Psiquiátrico', 'La+Primera+En+La+Frente') hecho
585:('Mötley+Crüe', 'Old+Skool+Of+Rock') hecho
600:('Nirvana', 'Nevermind') hecho
615:('Madonna', 'True+Blue') hecho
630:('Quiet+Riot', 'Metal+Health') hecho
645:('The+Clash', 'Combat+Rock') hecho
660:('Luis+Eduardo+Aute', 'Alma') hecho
675:('Macaco', 'Entre+Raíces+Y+Antenas') hecho
690:('Bryan+Adams', "18+'Til+I+Die") hecho
705:('Ace+Of+Base', 'The+Sign') hecho
720:('Marvin+Gaye+&+Tammi+Terrell', 'United') hecho
735:('Wild+Nothing', 'Gemini') hecho
750:('Stromae', 'Cheese') hecho
765:('Un+Pingüino+En+Mi+Ascensor', 'El+balneario') hecho
780:('Diamanda+Galás', 'Defixiones,+Will+and+Testament') hecho
795:('Backstreet+Boys', 'Backstreet+Boys') hecho
810:('Siniestro+Total', 'Ante+Todo,+Mucha+Calma') hecho
825:('Live', 'Mental+Jewelry') hecho
840:('Waylon+Jennings', "The+Ramblin'+Man") hecho
855:('Suzanne+Vega', 'Solitude+Standing') hecho
870:('Los+Nikis', 'Marines+a+pleno+sol') hecho
885:('Richard+Cheese', 'Lounge+Against+The+Machine') hecho
900:('Supertramp', 'Breakfast+in+America') hecho
915:('Echo+&+the+Bunnymen', 'Songs+to+Learn+&+Sing') hecho
930:('The+Kinks', 'Phobia') hecho
945:('Counting+Crows', 'Across+a+Wire:+Live+in+New+York') hecho
960:('Fritanga', 'Cuidado+que+quema') hecho
975:('Dolly+Parton', 'Slow+Dancing+With+The+Moon') hecho
990:('Brooks+&+Dunn', 'The+Essential+Brooks+&+Dunn') hecho
1005:('Shania+Twain', 'The+Woman+in+Me') hecho
1020:('Wade+Hayes', 'Old+Enough+To+Know+Better') hecho
1035:('Rage', 'Speak+Of+The+Dead') hecho
1065:('Soft+Cell', 'Non-Stop+Erotic+Cabaret') hecho
1080:('Amy+Dalley', "Love's+Really+Got+An+Attitude") hecho
1095:('Reba+McEntire', 'Reba:+Duets') hecho
1110:('Julie+Roberts', 'Men+&+Mascara') hecho
1125:('Dixie+Chicks', 'Fly') hecho
1140:('Reba+McEntire', 'Starting+Over') hecho
1155:('The+Beatles', "Beatles+'65") hecho
1170:('Blue+Öyster+Cult', 'Fire+of+Unknown+Origin') hecho
1185:('Brooks+&+Dunn', 'Brand+New+Man') hecho
1200:('Joni+Mitchell', 'Blue') hecho
1215:('Tim+McGraw', 'Live+Like+You+Were+Dying') hecho
1230:('Los+Secretos', 'Continuará') hecho
1245:('Pam+Tillis', 'Homeward+Looking+Angel') hecho
1260:('Kenny+Chesney', 'The+Road+and+the+Radio') hecho
1290:('Ronnie+Milsap', 'Lost+in+the+Fifties+Tonight') hecho
1305:('Clay+Walker', 'If+I+Could+Make+a+Living') hecho
1320:('Dolly+Parton', 'Rhinestone') hecho
1335:('Metallica', 'Garage+Inc.') hecho
1350:("The+B-52's", 'Cosmic+Thing') hecho
1365:('June+Carter+Cash', 'Wildwood+Flower') hecho
1380:('Sr.+Chinarro', 'El+Mundo+Según') hecho
1395:('Simon+&+Garfunkel', 'Bookends') hecho
1410:('The+Mighty+Mighty+Bosstones', "Where'd+You+Go?") hecho
1425:('Wham!', 'Make+It+Big') hecho
1440:('Los+Rodríguez', 'Buena+Suerte') hecho
1455:('Gabinete+Caligari', 'Privado') hecho
1470:('Skunk+Anansie', "You'll+Follow+Me+Down") hecho
1485:('Pet+Shop+Boys', 'Actually') hecho
1500:('Danza+Invisible', 'A+tu+alcance') hecho
1515:('TLC', 'Crazysexycool') hecho
1530:('Los+Suaves', 'Maldita+sea+mi+suerte') hecho
1545:('Tina+Turner', "We+Don't+Need+Another+Hero+(Thunderdome)") hecho
1560:('Kepa+Junkera', 'Etxea') hecho
1575:('Run-D.M.C.', 'Raising+Hell') hecho
1590:('Boyzone', 'By+Request') hecho
1605:('Florence+++the+Machine', 'Between+Two+Lungs') hecho
1620:('Harry+Belafonte', 'Calypso') hecho
1635:('Travis+Tritt', 'Country+Club') hecho
1650:('Lynn+Anderson', 'What+a+Man+My+Man+Is') hecho
1665:('Chambao', 'Con+otro+aire') hecho
1680:('Björk', 'Drawing+Restraint+9') hecho
1695:('Barricada', 'Noche+De+Rock+&+Roll') hecho
1710:('The+Doors', 'The+Doors') hecho
1725:('Jill+Johnson', 'Music+Row') hecho
1740:('Anton+Leuba', 'Under+Construction') hecho
1755:('Pitingo', 'Soulería') hecho
1770:('Rulo+y+la+contrabanda', 'Señales+de+humo') hecho
1785:('Joe+Crepúsculo', 'Nuevo+Ritmo') hecho
1800:('Petula+Clark', 'Les+Plus+Grands+Succès+De+Petula+Clark') hecho
1815:('Paco+de+Lucía', 'Paco+De+Lucía+y++Ramón+De+Algeciras+En+Hispanoamérica') hecho
1830:('Wisin+&+Yandel', 'Caribe+2009') hecho
1845:('Lucho+Gatica', 'Entre+Tinieblas') hecho
1860:('John+Denver', 'Back+Home+Again') hecho
1875:('Meteosat', 'Espunk!') hecho
1890:('Van+Morrison', 'Into+the+Music') hecho
1905:('Ten', 'The+Name+Of+The+Rose') hecho
1920:('Orishas', 'A+Lo+Cubano') hecho
1935:('Björk', 'Post') hecho
1950:('McNamara', 'Rockstation') hecho
1965:('Antonio+Vega', 'El+Sitio+de+mi+Recreo') hecho
1980:('The+Be+Good+Tanyas', 'Chinatown') hecho
1995:('Indeep', 'Last+Night+A+DJ+Saved+My+Life') hecho
2010:('Nicolas+Jaar', 'Space+Is+Only+Noise') hecho
2025:('Montell+Jordan', 'This+Is+How+We+Do+It') hecho
2040:('El+Fary', 'El+Fary') hecho
2055:('Mamá+Ladilla', 'Arzobispofobia') hecho
2070:('Arctic+Monkeys', 'Suck+It+And+See') hecho
2100:('Joni+Mitchell', 'Mingus') hecho
2115:('Sawyer+Brown', "This+Thing+Called+Wantin'+and+Havin'+It+All") hecho
2130:('Simple+Minds', "Don't+You+(Forget+About+Me)") hecho
2145:('Carrie+Underwood', 'Some+Hearts') hecho
2160:('Oasis', 'Heathen+Chemistry') hecho
2175:('George+Strait', 'Blue+Clear+Sky') hecho
2190:('Santana', 'Caravansarai') hecho
2205:('Oasis', 'Singles+++Demo') hecho
2220:('Jennifer+Lopez', 'On+the+6') hecho
2235:('U2', 'Zooropa') hecho
2250:('Santana', 'Aniversario') hecho
2265:('Skid+Row', 'B-Sides+Ourselves') hecho
2280:('Trace+Adkins', 'Dangerous+Man') hecho
2295:('Víctor+Jara', 'Canto+Libre') hecho
2310:('Bob+Dylan', 'Blonde+on+Blonde') hecho
2325:('Reel+Big+Fish', 'Baseketball+Soundtrack') hecho
2340:('Counting+Crows', 'This+Desert+Life') hecho
2355:('Jason+Mraz', 'Mr.+A-Z') hecho
2370:('David+Bowie', 'Bowie+at+the+Beeb') hecho
2385:('Joni+Mitchell+&+James+Taylor', 'Live+At+The+Royal+Albert+Hall') hecho
2400:('Arcadia', 'So+Red+the+Rose') hecho
2415:('Sertab+Erener', 'Masked+and+Anonymous') hecho
2430:('Thompson+Twins', 'Set') hecho
2445:('John+Mayer', 'Room+for+Squares') hecho
2460:('George+Harrison', 'Living+in+the+Material+World') hecho
2475:('Tokio+Hotel', 'Humanoid') hecho
2490:('Flobots', 'Survival+Story') hecho
2505:('Tin+Machine', 'Tin+Machine+II') hecho
2520:('Renée', 'The+future+none+can+see') hecho
2535:('Locomondo', '12+Meres+Sth+Jamaica') hecho
2550:('Crystal+Castles', 'Crimewave') hecho
2565:('Rev+Theory', 'Light+It+Up') hecho
2580:('Raimundo+Amador', 'Un+Okupa+En+Tu+Corazón') hecho
2595:('The+Offspring', '1st') hecho
2610:('Massive+Attack', 'Heligoland') hecho
2625:('The+Pussycat+Dolls', 'PCD') hecho
2640:('Rosendo', 'Veo,+veo...+Mamoneo!!') hecho
2655:('George+Harrison', 'Dark+Horse') hecho
2670:('Brynn+Marie', 'Start+Now') hecho

2685:('Lisa+Lisa+and+Cult+Jam', 'Straight+to+the+Sky') hecho
2700:('INXS', 'Welcome+To+Wherever+You+Are') hecho
2715:('La+Frontera', 'Nuevas+Aventuras') hecho
2730:('SHeDAISY', "Fortuneteller's+Melody") hecho
2745:('Buck+Owens', "I've+Got+a+Tiger+by+the+Tail") hecho
2760:('David+Lee+Roth', 'Sonrisa+Salvaje') hecho
2775:('The+Byrds', 'The+Notorious+Byrd+Brothers') hecho
2790:('The+Zombies', 'Odessey+&+Oracle') hecho
2805:("Destiny's+Child", '8+Days+of+Christmas') hecho
2835:('Andy+Griggs', "You+Won't+Ever+Be+Lonely") hecho
2850:('Katie+Noonan', 'Blackbird') hecho
2865:('The+Jimi+Hendrix+Experience', 'Are+You+Experienced?') hecho
2880:('J.B.O.', 'Laut') hecho
2895:('Loco+Mía', 'Taiyo') hecho
2910:('David+Bowie', 'Station+to+Station') hecho
2925:('Johnny+Russell', 'Rednecks,+White+Socks+And+Blue+Ribbon+Beer') hecho
2940:('Timi+Yuro', 'Hurt') hecho
2955:('Papá+Levante', 'Tomalacaté') hecho
2970:('Ryan+Paris', 'Dolce+vita') hecho
2985:('Bruce+Springsteen', 'The+River') hecho
3000:('Sonic+Youth', 'Sister') hecho
3015:('Katrina+and+the+Waves', 'Katrina+and+the+Waves') hecho
3030:('Ana+Torroja', 'Puntos+cardinales') hecho
3045:('Happy+Mondays', "Pills+'n'+Thrills+and+Bellyaches") hecho
3060:('Nick+Cave+&+The+Bad+Seeds', 'Abattoir+Blues/The+Lyre+Of+Orpheus') hecho
3075:('The+Sonics', 'Here+Are+the+Sonics!!!') hecho
error: 'results', {'message': 'You are making requests too quickly.'}, id = 3081
3090:('Morrissey', 'Ringleader+of+the+Tormentors') hecho
3105:('Alan+Parsons', 'Try+Anything+Once') hecho
3120:('Jason+Mraz', 'Love+Is+A+Four+Letter+Word') hecho
3135:('Firehouse', 'fROMOHIO') hecho
3150:('Matchbox+Twenty', 'North') hecho
3165:('The+Velvelettes', 'Come+See+About+Me') hecho
3180:('Theatre+of+Tragedy', 'Aégis') hecho
3195:('Alice+in+Chains', 'Dirt') hecho
3210:('Hinder', 'Extreme+Behavior') hecho
3225:('Extremoduro', 'Bajo+La+Corteza+(26+Canciones+De+Leño)') hecho
3240:('Mägo+de+Oz', 'Rarezas') hecho
3255:('Najwa', 'Donde+rugen+los+volcanes') hecho
3270:('The+Asteroids+Galaxy+Tour', 'Out+of+Frequency') hecho
3285:('Adele', '19') hecho
3300:('Iván+Ferreiro', 'Canciones+para+el+tiempo+y+la+distancia') hecho
3315:('Serge+Gainsbourg+and+Jane+Birkin', 'Jane+Birkin/Serge+Gainsbourg') hecho
3330:('Christina+Rosenvinge', 'La+Joven+Dolores') hecho
3345:('Quique+González', 'Pájaros+Mojados') hecho
3360:('Love+of+Lesbian', 'Maniobras+de+escapismo') hecho
3375:('Quique+González', 'Personal') hecho
3390:('Yurena', 'Go') hecho
3405:('Nuevo+Mester+Juglaría', '25+Aniversario') hecho
3420:('La+Llave+De+Allen', 'Como+ratones') hecho
3435:('Andrés+Lewin', 'Animales+y+aeropuertos') hecho
3450:('Lori+Meyers', 'Impronta') hecho
3465:('Desmadre+75', 'Aquí+está+el+güisqui,+cheli') hecho
3480:('Carlos+Vives', 'Clásicos+de+la+Provincia') hecho
3495:('Andrés+Calamaro', 'Bohemio') hecho
error: 'results', {'message': 'You are making requests too quickly.'}, id = 3501
3510:('Carlos+Chaouen', 'Universo+Abierto') hecho
3525:('Rancid', '...And+Out+Come+The+Wolves') hecho
3540:('Underworld', 'Second+Toughest+in+the+Infants') hecho
3555:('34+Puñaladas', 'Tangos+Carcelarios') hecho
3570:('NACH', 'Los+Viajes+Inmóviles') hecho
3585:('El+Columpio+Asesino', 'Ballenas+muertas+en+San+Sebastián') hecho
3600:('Will+Smith', 'Greatest+Hits') hecho
3615:('Siouxsie+and+the+Banshees', 'Juju') hecho
3630:('Leonard+Cohen', 'Popular+Problems') hecho
3645:('Miles+Kane', "Don't+Forget+Who+You+Are") hecho
3660:('Tahúres+Zurdos', 'Tahuría') hecho
3675:('Mini+Mansions', 'The+Great+Pretenders') hecho
3690:('Sufjan+Stevens', 'Carrie+&+Lowell') hecho
3705:('Echo+&+the+Bunnymen', 'Porcupine') hecho
3720:('Dr.+John,+the+Night+Tripper', 'Gris-Gris') hecho
3735:('The+Living+End', 'White+Noise') hecho
3750:('PJ+Harvey', 'Dry+&+Demonstration') hecho
3765:('Le+Parody', 'Hondo') hecho
3780:('Sleater-Kinney', 'No+Cities+To+Love') hecho
3795:('Suzanne+Vega', 'Suzanne+Vega') hecho
3810:('Small+Faces', "Ogden's+Nut+Gone+Flake") hecho
3825:('Elis+Regina', 'Vento+do+Maio') hecho
3840:('Emma+Pollock', 'In+Search+Of+Harperfield') hecho
3855:('Grimes', 'Visions') hecho
3870:('Love+of+Lesbian', 'El+Poeta+Halley') hecho
3885:('Elvis+Costello+&+The+Attractions', 'Imperial+Bedroom') hecho
3900:('Julianna+Barwick', 'Will') hecho
3915:('Olga+Bell', 'Tempo') hecho
3930:('Nick+Cave+&+The+Bad+Seeds', 'Skeleton+Tree') hecho
3945:('iamamiwhoami', 'kin') hecho
3960:('The+Sweet+Release+of+Death', 'The+Sweet+Release+of+Death') hecho
3975:('Lidia+Damunt', 'Telepatía') hecho
3990:('Laura+Marling', 'Semper+Femina') hecho
4005:('La+Bien+Querida', 'Ceremonia') hecho
4020:('Dolly+Parton', 'All+I+Can+Do') hecho
4035:('Triana', 'Triana') hecho
4050:('Miriam+Makeba', 'Makeba+Sings!') hecho
4065:('HAIM', 'Something+to+Tell+You') hecho
4080:('Charlotte+Gainsbourg', 'Rest') hecho
4095:('Rocío+Jurado', 'Señora') hecho
4110:('SOAK', 'Estado+de+Sitio') hecho
4125:('Zaz', 'Effet+Miroir') hecho
4140:('La+Maravillosa+Orquesta+del+Alcohol', 'Salvavida+(De+las+balas+perdidas)') hecho
4155:('dredg', 'Chuckles+and+Mr.+Squeezy') hecho
4170:('Kygo', 'Firestone') hecho
4185:('Soleá+Morente', 'Lo+Que+Te+Falta') hecho
4200:('One+Direction', 'Take+Me+Home') hecho
4215:('Javier+Álvarez', 'Grandes+éxitos') hecho
4230:('La+Maravillosa+Orquesta+del+Alcohol', 'No+Easy+Road') hecho
4245:('Los+Inhumanos', '30+Hombres+Solos') hecho
4260:('Emily+Wells', 'The+Symphonies:+Dreams+Memories+&+Parties') hecho
4275:('Nick+Drake', 'Bryter+Layter') hecho

In [33]:
lista[0:10]

[{'id_alb': 1, 'gen': 'Rock', 'genres': 'Rock', 'subgenres': nan},
 {'id_alb': 2,
  'gen': 'Rock',
  'genres': 'Rock,Pop',
  'subgenres': 'Blues Rock,Rock & Roll,Pop Rock'},
 {'id_alb': 3, 'gen': nan, 'genres': nan, 'subgenres': nan},
 {'id_alb': 4, 'gen': nan, 'genres': nan, 'subgenres': nan},
 {'id_alb': 5, 'gen': 'Pop', 'genres': 'Pop', 'subgenres': nan},
 {'id_alb': 6,
  'gen': 'Rock',
  'genres': 'Rock,Latin,Pop',
  'subgenres': 'Pop Rock,Rumba,Cumbia'},
 {'id_alb': 7, 'gen': 'Rock', 'genres': 'Rock,Pop', 'subgenres': nan},
 {'id_alb': 8, 'gen': 'Pop', 'genres': 'Pop', 'subgenres': nan},
 {'id_alb': 9, 'gen': 'Pop', 'genres': 'Pop', 'subgenres': nan},
 {'id_alb': 10, 'gen': 'Rock', 'genres': 'Rock,Pop', 'subgenres': 'Pop Rock'}]

In [34]:
generosdf = pd.DataFrame(lista)

In [36]:
generosdf.to_csv('output/generosdf.csv',index=False)

In [37]:
generosdf.sample(5)

,id_alb,gen,genres,subgenres
2568,2656,Rock,"Rock,Latin,Pop",NaN
533,558,Rock,"Rock,Latin,Folk, World, & Country",Folk
2077,2156,Rock,Rock,Blues Rock
471,495,Rock,Rock,Hard Rock
1156,1202,Jazz,"Jazz,Rock","Acoustic,Soft Rock,Folk Rock"

In [39]:
generosdf[generosdf['gen'] == 'error']

      id_alb    gen     genres subgenres
2980    3081  error  'results'     error
3394    3501  error  'results'     error

In [66]:
selec = generosdf[(generosdf['gen'].isna()==False)&(generosdf['gen'] != 'error')]

In [67]:
selec.shape

(3805, 4)

In [68]:
albums.shape

(4146, 5)

In [69]:
albums_genero = albums.merge(selec,how='left').drop(['art_url','alb_url'],axis=1)

In [70]:
albums_genero.to_csv('output/albums_genero.csv',index=False)

In [72]:
albums_genero = albums.merge(selec).drop(['art_url','alb_url'],axis=1)

In [73]:
albums_genero.head(5)

,artist,album,id_alb,gen,genres,subgenres
0,Siniestro Total,Made in Japan,1,Rock,Rock,NaN
1,Platero y tú,Hay Poco Rock & Roll,2,Rock,"Rock,Pop","Blues Rock,Rock & Roll,Pop Rock"
2,Niños Mutantes,Florecer,5,Pop,Pop,NaN
3,La Cabra Mecánica,Vestidos De Domingo,6,Rock,"Rock,Latin,Pop","Pop Rock,Rumba,Cumbia"
4,Joaquín Sabina,Nos Sobran Los Motivos,7,Rock,"Rock,Pop",NaN

In [83]:
albums_genero.artist.value_counts() > 1

Bob Dylan             True
David Bowie           True
Santana               True
The Kinks             True
The Beatles           True
                     ...
Fool's Garden        False
Luciano Pavarotti    False
Johnny Tillotson     False
Court Yard Hounds    False
Cutting Crew         False
Name: artist, Length: 1872, dtype: bool

In [90]:
repes = (albums_genero.artist.value_counts())

In [92]:
repes

Bob Dylan            34
David Bowie          34
Santana              29
The Kinks            27
The Beatles          27
                     ..
Fool's Garden         1
Luciano Pavarotti     1
Johnny Tillotson      1
Court Yard Hounds     1
Cutting Crew          1
Name: artist, Length: 1872, dtype: int64

In [95]:
dicc = {}
for key,value in repes.items():
    dicc[key] = value

In [97]:
albums_genero['rep_art'] = albums_genero.artist.map(dicc)

In [99]:
albums_genero[albums_genero['rep_art']>1]

,artist,album,id_alb,gen,genres,subgenres,rep_art
0,Siniestro Total,Made in Japan,1,Rock,Rock,NaN,5
1,Platero y tú,Hay Poco Rock & Roll,2,Rock,"Rock,Pop","Blues Rock,Rock & Roll,Pop Rock",8
2,Niños Mutantes,Florecer,5,Pop,Pop,NaN,7
3,La Cabra Mecánica,Vestidos De Domingo,6,Rock,"Rock,Latin,Pop","Pop Rock,Rumba,Cumbia",5
4,Joaquín Sabina,Nos Sobran Los Motivos,7,Rock,"Rock,Pop",NaN,11
...,...,...,...,...,...,...,...
3799,Amy Macdonald,Life in a Beautiful Light,4274,Rock,"Rock,Pop","Folk Rock,Acoustic,Pop Rock",3
3800,Nick Drake,Bryter Layter,4275,Rock,"Rock,Folk, World, & Country","Folk Rock,Folk",3
3801,Nick Drake,Five Leaves Left,4276,Rock,Rock,Folk Rock,3
3802,Fito & Fitipaldis,Cada Vez Cadáver,4278,Rock,Rock,"Classic Rock,Rock & Roll,Blues Rock",9
3803,Lana Del Rey,Blue Banisters,4279,Pop,Pop,Ballad,7

In [122]:
albums_genero[albums_genero['artist'] == 'Siniestro Total']['gen'].value_counts().keys()[0] #genero

'Rock'

In [125]:
albums_genero[albums_genero['artist'] == 'Siniestro Total']['gen'].value_counts().values[0] #cuenta

5

In [126]:
lista = []
for i,r in albums_genero.iterrows():
    dicc = {}
    dicc[id_alb] = r.id_alb
    dicc[]

SyntaxError: invalid syntax (<ipython-input-126-f846ca9a1ec0>, line 2)

In [ ]:
 {}